### ISSUE TITLE
playback of widewine (DRM) protected series

### ISSUE THREAD

**Issue by meskilla** [goggle/plugin.video.rtsplaytv#10]
RTS is no longer streaming us shows without drm protection, check against [Watchmen](https://www.rts.ch/play/recherche?query=Watchmen)

"Older" show like the rerun of [Westworld S3](https://www.rts.ch/play/recherche?query=Westworld) still use no drm.

Can it be included similar as the netflix plugin?

Edit1: Confirmed this works with widewine of InputStream.Helper, I just had to snatch the manifest mpd from my browser and add it to a strm file:

#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://srg.live.ott.irdeto.com/licenseServer/widevine/v1/SRG/license?contentId=RTSVOD|Content-Type=application/octet-stream|R{SSM}|
last line, here  you insert manifest.mpd url of your drm protected episode

there you go it plays ...

[https://github.com/xbmc/inputstream.adaptive/wiki/Integration](https://github.com/xbmc/inputstream.adaptive/wiki/Integration) should explain, how to implement this into python for a video addon

Edit2 tested against live stream of rts1 et rts2 ... just snatch the persistent mpd url as well from your browser and replace :inputstream.adaptive.license_key and it works as well, though resolution is not 720p but 544p like all drm streams I tested so far...

**Comment by goggle** [comment]
Thanks for reporting this. I wasn't aware that DRM is now needed for some regular shows.
I will try to get this supported.

**Comment by goggle** [comment]
`plugin.video.rtsplaytv` 2.2.0 will have support for this type of content. I will release it soon.

**Comment by goggle** [comment]
It will be in the official repo as soon as https://github.com/xbmc/repo-plugins/pull/4056 gets merged.
