### ISSUE TITLE
Live stream issues

### ISSUE THREAD

**Issue by claudep** [goggle/plugin.video.rtsplaytv#4]
First thanks for maintaining this add-on!

I have issues with live streams (also on my Linux desktop systems). It may be because of the introduction of DRM (https://rtsr.ch/digitalrightsmanagement/). Do you know if there is a potential fix for that?

**Comment by minibdm** [comment]
Hello,
Thanks a lot for your add-on.
But RTS1 and 2 direct are not working.
Live stream RTS sport, it's possible ?

**Comment by claudep** [comment]
Is this superseded by https://github.com/goggle/script.module.srgssr/issues/1 ?

**Comment by goggle** [comment]
As mentioned by @claudep, Live TV is not working anymore due to DRM prodection. I have opened an issue for this in the issue tracker of `script.module.srgssr`, see here: https://github.com/goggle/script.module.srgssr/issues/2

**Comment by goggle** [comment]
Live TV is currently not a goal of this plugin, is suggest to use `pvr.zattoo` for that.
